### ISSUE TITLE
After VITA upgrade wallet is not updating and I can't send

### ISSUE THREAD

**Issue by gucky25** [vidulum/vidulum#3]
After the VITA upgrade the GUI of the Wallet is is not updating.
I still receive coins from node, but I only can see it when I do a rescan of the transactions.
Sending and Shielding of coins is impossible, because the From is not filled and can't be filled.
Only think working okay is the maternode and I can see how long it is active.

Will these issues be solved with the new Wallet version or can I change this behavior in another way?

**Comment by Corey-Code** [comment]
@gucky25 We have just released our replacement wallet that will support the vita update. 

Please see: Win.Vidulum-Setup-v2.0.1.zip
In our releases on either this repo or our DesktopWallet repo
