### ISSUE TITLE
CreateNewBlock(): TestBlockValidity failed | Ah Ah Ah - no more selfish mining

### ISSUE THREAD

**Issue by laakie** [vidulum/vidulum#9]
Requesting block template fail 50% of the time, Leaving our pool in the dark about new work availability.
This failsafe should not trigger when requesting "getblocktemplate" ?

https://github.com/vidulum/vidulum/blob/8217fdf898fce1c2473fc71b45bc7cbb81052b7d/src/main.cpp#L4231

**Comment by Corey-Code** [comment]
Resolved on our Liquid Update.
